function [cellList] = getExtraDataLoop(cellList)
%Martin White, 2018

%This function calls the getextradata function of Oufti.  Make sure to add
%Oufti to the file path before running

%This function was generated by the Jacobs-Wagnor lab and copied from
%the Oufti forum.  

%The input ('cellList') is the variable cellList that is
%output from Oufti


for frameNumber = 1:length(cellList.meshData)
    for cellNumber = 1:length(cellList.meshData{frameNumber})
        %getextradata will check to make sure that the cell is valid, so no
        %need to check here
        cellList.meshData{frameNumber}{cellNumber} = getextradata(cellList.meshData{frameNumber}{cellNumber});
    end
end
end

